---

# This is the sensu-master's IP
rabbitmq_host_ip: 127.0.0.1
rabbitmq_host_port: 8159
rabbitmq_password: password

# If your RabbitMQ vhost or user are different than the default
# change them here
#rabbitmq_vhost: sensu
#rabbitmq_user: sensu
