---

- name: install Docker
  yum: name=docker state=latest
  tags: docker

- name: start docker
  service: name=docker state=started enabled=yes
  tags: docker

- name: download docker compose
  #shell: curl -L https://github.com/docker/compose/releases/download/1.1.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
  get_url:
    url="https://github.com/docker/compose/releases/download/1.1.0/docker-compose-Linux-x86_64"
    dest="/usr/local/bin/docker-compose"

- name: mod executable
  command: chmod +x /usr/local/bin/docker-compose
