---

# default password, generate using passlib, below is a sample
# python -c "from passlib.hash import sha512_crypt; import getpass; print sha512_crypt.encrypt(getpass.getpass())"
password: $6$rounds=100000$q6eBgkFOsL9TJKOF$g8p24Oo.Hv4BpgjIrDUBaTM6LZipuqvq8bMbMt6.SbU2Ds8mH6jWVUaqRADQSkq9CQwcFnsIMzxbI4aqfmFRM0

users:
  - name: jordan
    keys:
      - /home/jordan/.ssh/jordan.pub
    roles:
      - ssh_users
      - admins
      - wheel

# Management IPs or hosts, will be put in the fail2ban ssh.local jail config
# file as IP address to be ignored, i.e. not banned if too many login failures
# are made
# "ignoreip" can be an IP address, a CIDR mask or a DNS host
management_ips:
